#!/usr/bin/awk -f
#
# Old awk doesn't have rand() and srand()
#
# Script shows how random rand function is.
#
# Usage: awk -f randomawk

BEGIN {
        #srand(seed)
	i=0;
	while (i++<1000000) {
		x=int(rand()*100 + 0.5);
		y[x]++;
	}
	for (i=0;i<=100;i++) {
		printf("%d\t%d\n",y[i],i);
	}
	exit;
}
